default: &default
  adapter: postgresql
  username: desmond
  #password: 
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nyumbani_properties

test:
  <<: *default
  database: nyumbani_properties


production:
  <<: *default
  database: react_rails_api_project_template_production
  username: react_rails_api_project_template
  password: <%= ENV['REACT_RAILS_API_PROJECT_TEMPLATE_DATABASE_PASSWORD'] %>
